### ISSUE TITLE
Content Detail (Overseas Missionary)

### ISSUE THREAD

**Issue by lifeisox** [lifeisox/okcc.ca#28]
Object: 해외선교 (Overseas Missionary)
Contact: 최영우 ssamze@hotmail.com 316-6119

자료를 요청할 때 유의사항
1. 신규 홈페이지 개발에 대한 개요를 알림
2. 자료 마감일: 2월 9일
3. 장황한 텍스트보다는 간략하면서 핵심적인 정보를 제공 (A4 반 페이지를 초과하지 않는 범위)
4. 관련 사진: 디지털 이미지 3-10장
5. 샘플: [Sample webpage](https://churchome.org/gather/churchkids)

**Comment by ElwinKim** [comment]
아이티 선교 소개

지역: 아카에, 포르토프랭스, 와프제레미 지역
선교사: 이동열 (leedongyeol@gmail.com)
사역
초등학교, 중학교 영어수업 (Teaching English to Elementary/Middle School Students)
가정방문 전도사역 (Door-to-door Evangelism)
어린이 청소년 전도사역 (Children / Youth Ministry)
청소년 방과후 수업 (After-school Youth Ministry)
의료 사역 (Medical Ministry)
신학교 사역 (Seminary Ministry)

![33994866_10156240674153847_3355061145479151616_o](https://user-images.githubusercontent.com/42225354/53637686-d6e50080-3bf1-11e9-91d5-3eacd1003079.jpg)
![34071707_10156242777258847_4876220321272692736_o](https://user-images.githubusercontent.com/42225354/53637702-dea4a500-3bf1-11e9-8463-dec0c0869221.jpg)
![34138228_10156240674288847_1728898574873264128_o](https://user-images.githubusercontent.com/42225354/53637709-e19f9580-3bf1-11e9-83ef-c5ee20b986ad.jpg)

**Comment by ElwinKim** [comment]
니카라과 (마나구아 및 레온 지역)

 *   레온의 San Jose지역은 OKCC에서 2016년부터 지속적으로 지원함
 *   선교사: 박우석 (ppark0675@hanmail.net<mailto:ppark0675@hanmail.net>)
 *   사역
·          어린이 사역VBS
·          청소년 사역 Youth
·          여성 사역 Women
·          리더 교육 Leader
·         가정방문 전도 Evangelism
·         치과 사역 Dental
·         의료 사역 Medica

![img-3449](https://user-images.githubusercontent.com/42225354/53637777-0f84da00-3bf2-11e9-9a9e-7030cbca08a0.JPG)
![img-3448](https://user-images.githubusercontent.com/42225354/53637759-08f66280-3bf2-11e9-83f3-751ca03798d0.JPG)
![img-3450](https://user-images.githubusercontent.com/42225354/53637793-1c093280-3bf2-11e9-8132-d165117af773.JPG)

**Comment by lifeisox** [comment]
디자인에 반영하고 Close
