### ISSUE TITLE
Envisioning for Multilingual Wordpress

### ISSUE THREAD

**Issue by lifeisox** [lifeisox/okcc.ca#3]
Envisioning for multilingual Wordpress

우리교회는 English Ministry를 운영하기 때문에 영어권 선교에도 집중해야 하기 때문에 다국어 웹 사이트 개발이 필수입니다. 워드프레스에서 다국어 사이트를 만들 수 있는 다양한 방법이 있는데 어떤 방법이 우리에게 가장 적합한지 조사해야 함. 또한 다국어 개발을 위해 우리가 사전에 공유해야할 지식이 있는지, 있으면 무엇인지 조사하여 정보를 공유함.

참고할 웹 사이트: [The Ultimate Guide To Multilingual WordPress: WPML VS Polylang VS Multisite](https://blog.pojo.me/multilingual-wordpress/)

**Comment by kwkim80** [comment]
There are various Options

1 multi site
Advantages
- no conflict

Disadvantages
* can use other admin page
* difficult to maintain the site.

2 WPML
Advantages
- can use one admin page
- the most famous option for multi lanuage
- no limit with count of site and language
- manually make multi page
Disadvantages
* manual translate
* need to pay fee.
* speed issue
Fee policy
(This plugin has 3 different pricing plans: For Multilingual Blog costing $29 for the first year, for Multilingual CMS costing $79 for the first year, and a lifetime Multilingual CMS costing $195.)

3 Polylang 
Advantages
- can use one admin page
- for free
- manually make multipage
Disadvantages
* conflict with woocommerce 

4 Weglot Translate
Advantages
- small site is free (uder 2000 words)with one langaguage
- can translate website without any code
- Fully SEO compatible.
- support auto+manual translate
- automatic translate page
Disadvantages
- need to pay more than  something
- Korean not yet ?

5.  Google language translate
-  for free
- auto translate
- easy 
- result is not good.
- no compatible with SEO

**Comment by lifeisox** [comment]
이상하게 워드프레스 세상에서는 다국어 지원을 검색하면 <자동 번역> 기능으로 매치가 되네요. 사실 우리 홈페이지는 **번역 기능**이나 **복잡한 기능**은 필요없다고 생각합니다. (블로그는 한글 또는 영어로만, 작성자의 원본 의도에따라 지원할 예정입니다) 만약, 블로그 내용을 자동 번역하는 기능을 넣을 때는 선택의 여지가 없이 WPML을 사용해야할 것으로 보이네요.

기웅씨, 작성한 리포트를 Wiki에 올려 주세요. 

이 이슈는 완료되었으니 여기서 종료합니다.

**Comment by lifeisox** [comment]
아직 워드프레스에 대한 이해가 부족하여 더 연구할 필요가 있다고 생각되어 이 이슈를 다시 오픈합니다.

Version 1까지 시간이 많지 않아 가능현 다른 plugin에 대한 공부 없이 진행해보려고 합니다. 이걸 전제로 한다면 **멀티 사이트**(en.okcc.ca)가 더 적합한 솔루션인지도 모르겠습니다. 

다른 방법으로는 영어 페이지들의 경우 다른 header와 footer를 사용하도록 php 코딩을 하는 방법도 있네요.

**Comment by lifeisox** [comment]
멀티 사이트가 유일한 방법으로 사료됨
