### ISSUE TITLE
Content Detail (Local Missionary)

### ISSUE THREAD

**Issue by lifeisox** [lifeisox/okcc.ca#30]
Object: 도시선교 (Local Missionary)
Contact: 한영아 youngahahn2002@yahoo.ca 286-6984
특이사항: 도시선교는 새로 생긴 부서이며 이것이 이전 전도부(Local Missionary)인지 확실하지 않음.

자료를 요청할 때 유의사항
1. 신규 홈페이지 개발에 대한 개요를 알림
2. 자료 마감일: 2월 9일
3. 장황한 텍스트보다는 간략하면서 핵심적인 정보를 제공 (A4 반 페이지를 초과하지 않는 범위)
4. 관련 사진: 디지털 이미지 3-10장
5. 샘플: [Sample webpage](https://churchome.org/gather/churchkids)

**Comment by kwkim80** [comment]
[도시선교부.zip](https://github.com/lifeisox/okcc.ca/files/2971670/default.zip)

**Comment by lifeisox** [comment]
홈페이지 적용 완료 Close
