### ISSUE TITLE
Content Detail (Charity)

### ISSUE THREAD

**Issue by lifeisox** [lifeisox/okcc.ca#31]
Object: 구제 (Charity)
Contact: 이승환 seunghwanlee999@gmail.com 851-8781, 장명숙 emilyjang21@yahoo.ca 261-3905
특이사항: 구세군 점심 봉사, 농장 봉사 등 다양한 구제활동이 있으니 각 활동별로 사진과 활동을 수집하여야 함

자료를 요청할 때 유의사항
1. 신규 홈페이지 개발에 대한 개요를 알림
2. 자료 마감일: 2월 9일
3. 장황한 텍스트보다는 간략하면서 핵심적인 정보를 제공 (A4 반 페이지를 초과하지 않는 범위)
4. 관련 사진: 디지털 이미지 3-10장
5. 샘플: [Sample webpage](https://churchome.org/gather/churchkids)

**Comment by kwkim80** [comment]
[구제부 사역 소개 (1).docx](https://github.com/lifeisox/okcc.ca/files/2971610/1.docx)

**Comment by lifeisox** [comment]
디자인에 적용하고 Close
