### ISSUE TITLE
Envisioning for essential functionalities of church web site

### ISSUE THREAD

**Issue by lifeisox** [lifeisox/okcc.ca#4]
교회 웹 사이트가 필수적으로 가지고 있어야 할 기본 기능들을 조사함. 아래의 카테고리로 대분류하되 영어권과 한국 교회를 함께 조사해야 함

   - 현 출석 교인 및 가족 (People and their family who attend OKCC)
   - 출석을 고려하고 있는 예비 교인 (People who might attend your church)

**Comment by ElwinKim** [comment]
**Reference Websites**

- Toronto 영락교회 in Toronto(KOR)
- Bethel Church in Ottawa (ENG)
- Life.Church in US (ENG)
- 사랑의 교회 in Korea (KOR)

**현 출석 교인 및 가족 (People and their family who attend OKCC)**

교육 (Education & Bible studies)

- About church schools (Junior & senior)
- Bible study

Media/Resources ( 미디어 및 자료)

- Photo Album
- 구역예배 교재
- News

Sermon(설교)

- Sermon Archives(설교 자료)
- Sunday sermon(주일설교)
- Wednesday sermon(수요 설교)
- Friday sermon(금요 설교)

Events 

- Church events

Missions(선교/사역)

- Vision(비젼)
- Overseas(해외선교)
- Domestic(국내선교)
- Good News(선교지 소식)

Notice(공지사항)

**Comment by lifeisox** [comment]
[Content your church website must have](https://churchthemes.com/church-website-content/)
[Church Website Content](https://dlchurchwebsites.com/church-website-content/)

위 두 사이트도 참고하시고, 교회 웹 사이트에서 꼭 필요한 Content 추가해 주시고 위의 Content 중 빠져도 될 것 의견주세요. 이 게시물과 앞으로 추가될 Comment를 토대로 Site Map을 만들어 갈 예정입니다.

**Comment by ElwinKim** [comment]
**Reference Websites**

-  Toronto 영락교회 in Toronto(KOR)
-  Bethel Church in Ottawa (ENG)
-  Life.Church in US (ENG)
-  사랑의 교회 in Korea (KOR)

**출석을 고려하고 있는 예비 교인 (People who might attend your church)**

I'm New(For first visit)

- Resister(등록절차)
- Jesus (예수님이란)
- What we believe(교회 비젼 및 믿음)

About church(교회소개)

- Worship(예배시간)
- History(교회연혁)
- Ministers & staffs( 사역자들)
- Baptism

Ministries

- Senior 
- Young adult 
- Youth 
- Kids

Location(오시는길)

Sitemap

**Comment by ElwinKim** [comment]
토론토 영락교회
http://www.torontoyoungnak.com/index_v2.php

Bethel Church
https://www.bethel.com/

Life Church
https://www.life.church/

사랑의 교회
https://www.sarang.org/

Please find attached file. 
Thank you very much.
[sitemap_reference.docx](https://github.com/lifeisox/okcc.ca/files/2724510/sitemap_reference.docx)

**Comment by kwkim80** [comment]
현 출석 교인 및 가족 (People and their family who attend OKCC)
출석을 고려하고 있는 예비 교인 (People who might attend your church)

분류하게  되면 
New랑 현재교인이랑  보여지는  메뉴가  차이가  있나요?
저희 교인들   로그인을  하고  사이트를  이용하는건가요? 어니면  로그인없이  이용인가요?

**Comment by lifeisox** [comment]
일단, 4월까지 개발하는 Version 1은 로그인 없이 사용하는 메뉴만 넣어 개발할 예정입니다. 블로그, 앨범, 교회 소식지 등도 관리자가 직접 포스팅하는 방법을 사용하겠습니다.

그리고, 현출석교인 메뉴와 예비교인을 위한 메뉴에 중복되는 Content가 있을 수 있습니다.

1. 조사한 Content 중 버전 1에 넣을 것 뺄 것을 분별해야 하고,
2. 추가로 포함할 Content가 있으면 Add 해 주세요.

**Comment by lifeisox** [comment]
Based on the report written by Byung-jin Kim, I created an initial version of the OKCC site map. Please check all collaborators and reply to the menu that needs to be added, changed or deleted. Exact terms (both Korean and English) will be defined in Sitemap issues.

김병진 위원이 작성한 리포트를 토대로 사이트맵의 초기버전을 만들어 보았습니다. 위원들 모두 꼭 확인해보시고, 더 추가하거나 변경, 삭제할 필요가 있는 메뉴 답글 바랍니다. 정확한 용어의 표현(한글, 영어 모두)은 Sitemap 이슈에서 정하도록 하겠습니다.

1. 새신자 환영 / I am New (For the first visit)
	- 새신자 환영 /  I am New (For first visit) 대문 페이지
	- 새신자 등록 / 등록절차 / Registeration
	- 교회 안내 / What we believe
	- 오시는 길 / 약도 / Location
	- 주차 안내 / Where they should park - 추가
	- 자모실, 유아반 운영 / Is child care available? - 추가
	- 친교실 운영 / Fellowship - 추가
	- 예배시간 / Service Time
	- 사역자들 / 섬기는 사람들 / Ministers & Staffs / Leadership
	- 문의사항 / Contact Information - 추가
	
2. 교회소개 / About Us
	- 교회소개 / About Us 대문 페이지
	- 2019년 교회 목표 ------> 추가
	- 오시는 길 / 약도 / Location
	- 예배시간 / Service Time
	- 교회연혁 / History

3. 예배 및 찬양 / Worship	
	- 예배 및 찬양 / Worship 대문 페이지
	- 주일설교 / Sunday sermon
	- 찬양 / Praise - 추가
	- 교회주보 /
	
4. 이벤트 / Events
	- 2019년 교회 이벤트 / '2019 Church Events
	- 예배시간 / Service Time
	- 앨범 / Photo Gallery

5. 양육 및 훈련 / 교육 / Education & Bible studies / Discipline
	- 양육 및 훈련 / 교육 / Education & Bible studies / Discipline 대문 페이지
	- 유치부 / Ainos
	- 초등부 / Pilloy
	- 중고등부 / Youth
	- 청년부 / Bahurim
	- 영어부 / Mosaic / English Ministry
	- 성인성경공부 (성인 성경공부 및 제자 훈련) / Adult Bible Study & Discipleship Training / Desciple Maker
	
6. 선교와 사역 / Ministries / Missions - 정확한 title과 용어를 부서로부터 제공 받아야 할 것으로 보임
	- 선교와 사역 / Ministries / Missions 대문 페이지 (Vision)
	- 해외선교 / Overseas
	- 원주민 선교 / 
	- 국내선교 / Domestic : 구세군 단체 노숙자 점심 봉사, 농장 봉사, 부탄 교회, 아라빅, 난민 구제 등
	- 구세군 단체 지원 / Salvation Army 

7. 블로그 / Blog

0. 문의사항 / Contact Information - in Footer

0. 사이트맵 / Sitemap - in Footer

- Jesus (예수님이란): 교회 안내 / what we believe 와 중복
- Baptism: 무엇인지 모르겠음
- Sermon Archives(설교 자료): 목사님들이 업로드하는 공간으로 예상되지만 이것은 추후 버전으로...
- Wednesday sermon(수요 설교): 방송부에서 촬영하지 않음
- Friday sermon(금요 설교): 방송부에서 촬영하지 않음
- 관리자 이외의 사람이 업로드해야하는 경우의 메뉴는 삭제하였음. (예: 구역예배 교재)
- 나머지는 교회 현실에 맞춰 조금씩 변경하였음. (예: 교육, 선교 관련 메뉴)

**Comment by lifeisox** [comment]
아무도 의견 없으시니 이 이슈는 Close하고 사이트맵 초기버전을 사이트맵 Issue로 이전하여 계속 논의하겠습니다.
